
/run/initialize

/vis/open OGL 600x600-0+0

/vis/viewer/set/viewpointVector 0 0 1
/vis/viewer/set/autoRefresh true

/vis/drawVolume

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set mu- cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pi- green
/vis/modeling/trajectories/drawByParticleID-0/set pi+ orange
/vis/modeling/trajectories/drawByParticleID-0/set neutron white
/vis/modeling/trajectories/drawByParticleID-0/set proton gray



/vis/scene/endOfEventAction accumulate
/vis/scene/add/eventID


